package com.petfeeding.server.dal.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.customer_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.servant_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Integer servantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Boolean orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.distance
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Integer distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pet_number
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Integer petNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.feeding_cost
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Float feedingCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.payment_mode
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private String paymentMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.satisfaction
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Integer satisfaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.evaluation
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private String evaluation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_at
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_at
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.customer_id
     *
     * @return the value of order.customer_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.customer_id
     *
     * @param customerId the value for order.customer_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.servant_id
     *
     * @return the value of order.servant_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Integer getServantId() {
        return servantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.servant_id
     *
     * @param servantId the value for order.servant_id
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setServantId(Integer servantId) {
        this.servantId = servantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @return the value of order.order_status
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Boolean getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_status
     *
     * @param orderStatus the value for order.order_status
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setOrderStatus(Boolean orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.distance
     *
     * @return the value of order.distance
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.distance
     *
     * @param distance the value for order.distance
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pet_number
     *
     * @return the value of order.pet_number
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Integer getPetNumber() {
        return petNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pet_number
     *
     * @param petNumber the value for order.pet_number
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setPetNumber(Integer petNumber) {
        this.petNumber = petNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.feeding_cost
     *
     * @return the value of order.feeding_cost
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Float getFeedingCost() {
        return feedingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.feeding_cost
     *
     * @param feedingCost the value for order.feeding_cost
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setFeedingCost(Float feedingCost) {
        this.feedingCost = feedingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.payment_mode
     *
     * @return the value of order.payment_mode
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public String getPaymentMode() {
        return paymentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.payment_mode
     *
     * @param paymentMode the value for order.payment_mode
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.satisfaction
     *
     * @return the value of order.satisfaction
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Integer getSatisfaction() {
        return satisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.satisfaction
     *
     * @param satisfaction the value for order.satisfaction
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setSatisfaction(Integer satisfaction) {
        this.satisfaction = satisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.evaluation
     *
     * @return the value of order.evaluation
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.evaluation
     *
     * @param evaluation the value for order.evaluation
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_at
     *
     * @return the value of order.create_at
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_at
     *
     * @param createAt the value for order.create_at
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_at
     *
     * @return the value of order.update_at
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_at
     *
     * @param updateAt the value for order.update_at
     *
     * @mbg.generated Mon Jan 20 16:13:22 CST 2020
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}