/* SQLEditor (MySQL (2))*/


CREATE TABLE user
(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  user_name VARCHAR(16) NOT NULL UNIQUE ,
  password VARCHAR(32) NOT NULL,
  gender TINYINT(0) NOT NULL,
  phone_number INTEGER(11) UNSIGNED NOT NULL UNIQUE ,
  user_role TINYINT(1) NOT NULL DEFAULT 0,
  user_address VARCHAR(256),
  create_at DATETIME NOT NULL,
  update_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);

